### ISSUE TITLE
Show all results when there is no search phrase 

### ISSUE THREAD

**Issue by mateusz0matti** [daniel-maxhari/dynamic_text_highlighting#3]
Hi,

I use this widget to show searching results but when searchbox is empty, I would like to show all data, not an empty list.
Now I need to wrap my list item with this widget only when searching phrase is not empty.

Can you do something to solve it?

ps. Thanks for case sensitive option

**Comment by maxhda-studio** [comment]
Hi, you are welcome! I think this could be done outside the package.
In fact, Dynamic Text Highlighting let's you to highlight a text, but you decide how to do this.
Let me know if this was OK.
